# Generated by Django 4.2.4 on 2023-08-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_alter_club_id_alter_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='next_call',
            field=models.CharField(choices=[('P', 'portiere'), ('D', 'difensore'), ('C', 'centrocampista'), ('A', 'attaccante')], max_length=1, null=True),
        ),
    ]
