# Generated by Django 4.2.4 on 2023-09-02 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_club_next_call'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['name']},
        ),
    ]
